# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: chain check and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: peqpone/YamSolo/actions/check-only
    - uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: '${{ secrets.SFTP_USERNAME }}'
        server: '${{ secrets.SFTP_SERVER }}'
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: './dist/*'
        remote_path: '/home/peqpeuo/yamsolo'
        delete_remote_files: true
        sftpArgs: '-o ConnectTimeout=5'
